CREATE TABLE Users (
    UserID INT PRIMARY KEY IDENTITY(1,1) NULL,
    UserName NVARCHAR(100) NULL,
    UserEmail NVARCHAR(100) NULL UNIQUE,
    Password NVARCHAR(100) NULL,
    Role NVARCHAR(50) NULL
);